# Signal Hub Development Configuration

server:
  host: "localhost"
  port: 3333
  name: "Signal Hub (Dev)"
  description: "Intelligent MCP server for RAG-enhanced development"

logging:
  level: "DEBUG"
  format: "detailed"
  file: "logs/signal-hub-dev.log"

storage:
  type: "chromadb"
  path: "./data/chroma"
  collection: "signal_hub_dev"

embedding:
  provider: "openai"
  model: "text-embedding-ada-002"
  batch_size: 100
  cache_enabled: true

indexing:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size_mb: 10
  ignored_patterns:
    - "*.pyc"
    - "__pycache__"
    - ".git"
    - ".venv"
    - "node_modules"
    - "*.log"

model_routing:
  default_model: "haiku"
  complexity_thresholds:
    simple: 0.3
    medium: 0.7
  models:
    haiku:
      name: "claude-3-haiku-20240307"
      max_tokens: 4096
    sonnet:
      name: "claude-3-sonnet-20240229"
      max_tokens: 4096
    opus:
      name: "claude-3-opus-20240229"
      max_tokens: 4096

cache:
  enabled: true
  ttl_seconds: 3600
  max_size_mb: 500