# Signal Hub Development Configuration

# Edition: basic, pro, or enterprise
# Set SIGNAL_HUB_EDITION environment variable or configure here
edition: "basic"

# Early access mode - enables all features for testing
# Set SIGNAL_HUB_EARLY_ACCESS=true to enable
early_access: false

server:
  host: "localhost"
  port: 3333
  name: "Signal Hub Basic (Dev)"
  description: "Intelligent MCP server for RAG-enhanced development"

logging:
  level: "DEBUG"
  format: "detailed"
  file: "logs/signal-hub-dev.log"

storage:
  type: "chromadb"
  path: "./data/chroma"
  collection: "signal_hub_dev"

embedding:
  provider: "openai"
  model: "text-embedding-ada-002"
  batch_size: 100
  cache_enabled: true

indexing:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size_mb: 10
  ignored_patterns:
    - "*.pyc"
    - "__pycache__"
    - ".git"
    - ".venv"
    - "node_modules"
    - "*.log"

model_routing:
  default_model: "haiku"
  complexity_thresholds:
    simple: 0.3
    medium: 0.7
  models:
    haiku:
      name: "claude-3-haiku-20240307"
      max_tokens: 4096
    sonnet:
      name: "claude-3-sonnet-20240229"
      max_tokens: 4096
    opus:
      name: "claude-3-opus-20240229"
      max_tokens: 4096

cache:
  enabled: true
  ttl_seconds: 3600
  max_size_mb: 500

# Plugin configuration
plugins:
  # Basic plugins (always enabled)
  basic_router:
    enabled: true
  basic_cache:
    enabled: true
  basic_analytics:
    enabled: true
  
  # Pro plugins (require pro edition or early access)
  ml_router:
    enabled: false
    model_path: "./models/routing_model.pkl"
  advanced_analytics:
    enabled: false
    dashboard_port: 8080

# Feature flags (override default feature availability)
features:
  # Enable specific pro features for testing
  ml_routing_enabled: false
  advanced_analytics_enabled: false